/*
 * SudokuPanel.java
 *
 * Created on 24. Juli 2006, 14:04
 */

package straitjacket.gui;

import javax.swing.*;

/**
 *
 * @author  peach
 */
class SudokuPanel extends javax.swing.JPanel {
    
    private javax.swing.JFormattedTextField[][] textFieldMatrix;
    private final javax.swing.text.NumberFormatter integerFormatter;
    
    /** Creates new form SudokuPanel */
    public SudokuPanel() {
        
        // init the numberFormatter
        java.text.NumberFormat nf = java.text.NumberFormat.getIntegerInstance();
        nf.setMaximumIntegerDigits(1);
        nf.setMaximumIntegerDigits(1);
        nf.setParseIntegerOnly(true);
        integerFormatter = new javax.swing.text.NumberFormatter(nf);
        
        initComponents();
        // we build up a matrix with the textfields
        // redundancy -- i know... this is to let the code 
        // generated by netbeans untouched... thus matisse
        // can still be used
        initMatrix();
    }
    
    public java.awt.Dimension getPreferredSize() {
        return new java.awt.Dimension(400,400);
    }
    
    void initMatrix() {
        textFieldMatrix = new javax.swing.JFormattedTextField[9][9];
        textFieldMatrix[0][0] = jFormattedTextField1;
        textFieldMatrix[0][1] = jFormattedTextField2;
        textFieldMatrix[0][2] = jFormattedTextField3;
        textFieldMatrix[0][3] = jFormattedTextField4;
        textFieldMatrix[0][4] = jFormattedTextField5;
        textFieldMatrix[0][5] = jFormattedTextField6;
        textFieldMatrix[0][6] = jFormattedTextField7;
        textFieldMatrix[0][7] = jFormattedTextField8;
        textFieldMatrix[0][8] = jFormattedTextField9;
        textFieldMatrix[1][0] = jFormattedTextField10;
        textFieldMatrix[1][1] = jFormattedTextField11;
        textFieldMatrix[1][2] = jFormattedTextField12;
        textFieldMatrix[1][3] = jFormattedTextField13;
        textFieldMatrix[1][4] = jFormattedTextField14;
        textFieldMatrix[1][5] = jFormattedTextField15;
        textFieldMatrix[1][6] = jFormattedTextField16;
        textFieldMatrix[1][7] = jFormattedTextField17;
        textFieldMatrix[1][8] = jFormattedTextField18;
        textFieldMatrix[2][0] = jFormattedTextField19;
        textFieldMatrix[2][1] = jFormattedTextField20;
        textFieldMatrix[2][2] = jFormattedTextField21;
        textFieldMatrix[2][3] = jFormattedTextField22;
        textFieldMatrix[2][4] = jFormattedTextField23;
        textFieldMatrix[2][5] = jFormattedTextField24;
        textFieldMatrix[2][6] = jFormattedTextField25;
        textFieldMatrix[2][7] = jFormattedTextField26;
        textFieldMatrix[2][8] = jFormattedTextField27;
        textFieldMatrix[3][0] = jFormattedTextField28;
        textFieldMatrix[3][1] = jFormattedTextField29;
        textFieldMatrix[3][2] = jFormattedTextField30;
        textFieldMatrix[3][3] = jFormattedTextField31;
        textFieldMatrix[3][4] = jFormattedTextField32;
        textFieldMatrix[3][5] = jFormattedTextField33;
        textFieldMatrix[3][6] = jFormattedTextField34;
        textFieldMatrix[3][7] = jFormattedTextField35;
        textFieldMatrix[3][8] = jFormattedTextField36;
        textFieldMatrix[4][0] = jFormattedTextField37;
        textFieldMatrix[4][1] = jFormattedTextField38;
        textFieldMatrix[4][2] = jFormattedTextField39;
        textFieldMatrix[4][3] = jFormattedTextField40;
        textFieldMatrix[4][4] = jFormattedTextField41;
        textFieldMatrix[4][5] = jFormattedTextField42;
        textFieldMatrix[4][6] = jFormattedTextField43;
        textFieldMatrix[4][7] = jFormattedTextField44;
        textFieldMatrix[4][8] = jFormattedTextField45;
        textFieldMatrix[5][0] = jFormattedTextField46;
        textFieldMatrix[5][1] = jFormattedTextField47;
        textFieldMatrix[5][2] = jFormattedTextField48;
        textFieldMatrix[5][3] = jFormattedTextField49;
        textFieldMatrix[5][4] = jFormattedTextField50;
        textFieldMatrix[5][5] = jFormattedTextField51;
        textFieldMatrix[5][6] = jFormattedTextField52;
        textFieldMatrix[5][7] = jFormattedTextField53;
        textFieldMatrix[5][8] = jFormattedTextField54;
        textFieldMatrix[6][0] = jFormattedTextField55;
        textFieldMatrix[6][1] = jFormattedTextField56;
        textFieldMatrix[6][2] = jFormattedTextField57;
        textFieldMatrix[6][3] = jFormattedTextField58;
        textFieldMatrix[6][4] = jFormattedTextField59;
        textFieldMatrix[6][5] = jFormattedTextField60;
        textFieldMatrix[6][6] = jFormattedTextField61;
        textFieldMatrix[6][7] = jFormattedTextField62;
        textFieldMatrix[6][8] = jFormattedTextField63;
        textFieldMatrix[7][0] = jFormattedTextField64;
        textFieldMatrix[7][1] = jFormattedTextField65;
        textFieldMatrix[7][2] = jFormattedTextField66;
        textFieldMatrix[7][3] = jFormattedTextField67;
        textFieldMatrix[7][4] = jFormattedTextField68;
        textFieldMatrix[7][5] = jFormattedTextField69;
        textFieldMatrix[7][6] = jFormattedTextField70;
        textFieldMatrix[7][7] = jFormattedTextField71;
        textFieldMatrix[7][8] = jFormattedTextField72;
        textFieldMatrix[8][0] = jFormattedTextField73;
        textFieldMatrix[8][1] = jFormattedTextField74;
        textFieldMatrix[8][2] = jFormattedTextField75;
        textFieldMatrix[8][3] = jFormattedTextField76;
        textFieldMatrix[8][4] = jFormattedTextField77;
        textFieldMatrix[8][5] = jFormattedTextField78;
        textFieldMatrix[8][6] = jFormattedTextField79;
        textFieldMatrix[8][7] = jFormattedTextField80;
        textFieldMatrix[8][8] = jFormattedTextField81;
    }
    
    public int getBlockSize() {
        return 3;
    }
    
    public int getFieldSize() {
        return 9;
    }
    
    public void setValueAt(int x, int y, Object o) {
        this.textFieldMatrix[x][y].setValue( o );
    }
    
    public String getValueAt(int x, int y) {
        Object o = this.textFieldMatrix[x][y].getValue();
        return o == null ? null : this.textFieldMatrix[x][y].getValue().toString();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jFormattedTextField1 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField2 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField3 = new javax.swing.JFormattedTextField( integerFormatter );
        JSeparator jSeparator1 = new JSeparator();
        jFormattedTextField4 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField5 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField6 = new javax.swing.JFormattedTextField( integerFormatter );
        JSeparator jSeparator2 = new JSeparator();
        jFormattedTextField7 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField8 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField9 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField10 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField11 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField12 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField13 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField14 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField15 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField16 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField17 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField18 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField19 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField20 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField21 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField22 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField23 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField24 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField25 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField26 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField27 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField28 = new javax.swing.JFormattedTextField( integerFormatter );
        JSeparator jSeparator3 = new JSeparator();
        jFormattedTextField29 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField30 = new javax.swing.JFormattedTextField( integerFormatter );
        JSeparator jSeparator4 = new JSeparator();
        jFormattedTextField31 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField32 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField33 = new javax.swing.JFormattedTextField( integerFormatter );
        JSeparator jSeparator5 = new JSeparator();
        jFormattedTextField34 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField35 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField36 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField37 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField38 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField39 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField40 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField41 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField42 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField43 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField44 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField45 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField46 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField47 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField48 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField49 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField50 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField51 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField52 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField53 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField54 = new javax.swing.JFormattedTextField( integerFormatter );
        JSeparator jSeparator6 = new JSeparator();
        jFormattedTextField55 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField56 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField57 = new javax.swing.JFormattedTextField( integerFormatter );
        JSeparator jSeparator7 = new JSeparator();
        jFormattedTextField58 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField59 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField60 = new javax.swing.JFormattedTextField( integerFormatter );
        JSeparator jSeparator8 = new JSeparator();
        jFormattedTextField61 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField62 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField63 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField64 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField65 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField66 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField67 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField68 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField69 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField70 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField71 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField72 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField73 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField74 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField75 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField76 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField77 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField78 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField79 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField80 = new javax.swing.JFormattedTextField( integerFormatter );
        jFormattedTextField81 = new javax.swing.JFormattedTextField( integerFormatter );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jFormattedTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jFormattedTextField10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jFormattedTextField19, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField20, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField21, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField22, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField24, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField16, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField17, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField25, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField26, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField27, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                        .add(1, 1, 1))
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField28, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField29, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField30, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jFormattedTextField46, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .add(jFormattedTextField37, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jFormattedTextField38, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jFormattedTextField39, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                    .add(layout.createSequentialGroup()
                                        .add(jFormattedTextField47, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jFormattedTextField48, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))))
                        .add(12, 12, 12)
                        .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField31, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField32, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField33, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField40, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField41, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField42, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField49, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField50, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField51, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField52, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField53, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField54, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField43, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField44, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField45, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField34, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField35, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField36, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                        .add(1, 1, 1))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField55, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField56, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField57, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField64, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField65, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField66, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField73, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField74, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField75, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField58, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField59, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField60, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField67, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField68, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField69, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField76, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField77, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField78, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField79, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField80, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField81, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField61, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField62, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField63, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jFormattedTextField70, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField71, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextField72, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                        .add(1, 1, 1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(26, 26, 26))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jFormattedTextField7)
                                            .add(jFormattedTextField8)
                                            .add(jFormattedTextField9))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jFormattedTextField16)
                                            .add(jFormattedTextField17)
                                            .add(jFormattedTextField18))
                                        .add(30, 30, 30))
                                    .add(layout.createSequentialGroup()
                                        .add(60, 60, 60)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jFormattedTextField25)
                                            .add(jFormattedTextField26)
                                            .add(jFormattedTextField27)))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jFormattedTextField4)
                                            .add(jFormattedTextField5)
                                            .add(jFormattedTextField6))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jFormattedTextField13)
                                            .add(jFormattedTextField14)
                                            .add(jFormattedTextField15))
                                        .add(30, 30, 30))
                                    .add(layout.createSequentialGroup()
                                        .add(60, 60, 60)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jFormattedTextField22)
                                            .add(jFormattedTextField23)
                                            .add(jFormattedTextField24)))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jFormattedTextField1)
                                            .add(jFormattedTextField2)
                                            .add(jFormattedTextField3))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jFormattedTextField10)
                                            .add(jFormattedTextField11)
                                            .add(jFormattedTextField12))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jFormattedTextField19)
                                            .add(jFormattedTextField20)
                                            .add(jFormattedTextField21))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(12, 12, 12))
                            .add(layout.createSequentialGroup()
                                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(27, 27, 27)))
                        .add(0, 0, 0)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jFormattedTextField28)
                            .add(jFormattedTextField29)
                            .add(jFormattedTextField30))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jFormattedTextField37)
                            .add(jFormattedTextField38)
                            .add(jFormattedTextField39))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jFormattedTextField46)
                            .add(jFormattedTextField47)
                            .add(jFormattedTextField48)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jFormattedTextField31)
                            .add(jFormattedTextField32)
                            .add(jFormattedTextField33))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jFormattedTextField40)
                            .add(jFormattedTextField41)
                            .add(jFormattedTextField42))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jFormattedTextField49)
                            .add(jFormattedTextField50)
                            .add(jFormattedTextField51)))
                    .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jFormattedTextField34)
                            .add(jFormattedTextField35)
                            .add(jFormattedTextField36))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jFormattedTextField43)
                            .add(jFormattedTextField44)
                            .add(jFormattedTextField45))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jFormattedTextField52)
                            .add(jFormattedTextField53)
                            .add(jFormattedTextField54))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFormattedTextField55)
                                    .add(jFormattedTextField56)
                                    .add(jFormattedTextField57))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFormattedTextField64)
                                    .add(jFormattedTextField65)
                                    .add(jFormattedTextField66))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFormattedTextField74)
                                    .add(jFormattedTextField73)
                                    .add(jFormattedTextField75)))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFormattedTextField58)
                                    .add(jFormattedTextField59)
                                    .add(jFormattedTextField60))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFormattedTextField67)
                                    .add(jFormattedTextField68)
                                    .add(jFormattedTextField69))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFormattedTextField76)
                                    .add(jFormattedTextField77)
                                    .add(jFormattedTextField78))))
                        .add(1, 1, 1))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFormattedTextField61)
                                    .add(jFormattedTextField62)
                                    .add(jFormattedTextField63))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFormattedTextField70)
                                    .add(jFormattedTextField71)
                                    .add(jFormattedTextField72))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jFormattedTextField79)
                                    .add(jFormattedTextField80)
                                    .add(jFormattedTextField81)))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(1, 1, 1))
                    .add(jSeparator7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField20;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField23;
    private javax.swing.JFormattedTextField jFormattedTextField24;
    private javax.swing.JFormattedTextField jFormattedTextField25;
    private javax.swing.JFormattedTextField jFormattedTextField26;
    private javax.swing.JFormattedTextField jFormattedTextField27;
    private javax.swing.JFormattedTextField jFormattedTextField28;
    private javax.swing.JFormattedTextField jFormattedTextField29;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField30;
    private javax.swing.JFormattedTextField jFormattedTextField31;
    private javax.swing.JFormattedTextField jFormattedTextField32;
    private javax.swing.JFormattedTextField jFormattedTextField33;
    private javax.swing.JFormattedTextField jFormattedTextField34;
    private javax.swing.JFormattedTextField jFormattedTextField35;
    private javax.swing.JFormattedTextField jFormattedTextField36;
    private javax.swing.JFormattedTextField jFormattedTextField37;
    private javax.swing.JFormattedTextField jFormattedTextField38;
    private javax.swing.JFormattedTextField jFormattedTextField39;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField40;
    private javax.swing.JFormattedTextField jFormattedTextField41;
    private javax.swing.JFormattedTextField jFormattedTextField42;
    private javax.swing.JFormattedTextField jFormattedTextField43;
    private javax.swing.JFormattedTextField jFormattedTextField44;
    private javax.swing.JFormattedTextField jFormattedTextField45;
    private javax.swing.JFormattedTextField jFormattedTextField46;
    private javax.swing.JFormattedTextField jFormattedTextField47;
    private javax.swing.JFormattedTextField jFormattedTextField48;
    private javax.swing.JFormattedTextField jFormattedTextField49;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField50;
    private javax.swing.JFormattedTextField jFormattedTextField51;
    private javax.swing.JFormattedTextField jFormattedTextField52;
    private javax.swing.JFormattedTextField jFormattedTextField53;
    private javax.swing.JFormattedTextField jFormattedTextField54;
    private javax.swing.JFormattedTextField jFormattedTextField55;
    private javax.swing.JFormattedTextField jFormattedTextField56;
    private javax.swing.JFormattedTextField jFormattedTextField57;
    private javax.swing.JFormattedTextField jFormattedTextField58;
    private javax.swing.JFormattedTextField jFormattedTextField59;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField60;
    private javax.swing.JFormattedTextField jFormattedTextField61;
    private javax.swing.JFormattedTextField jFormattedTextField62;
    private javax.swing.JFormattedTextField jFormattedTextField63;
    private javax.swing.JFormattedTextField jFormattedTextField64;
    private javax.swing.JFormattedTextField jFormattedTextField65;
    private javax.swing.JFormattedTextField jFormattedTextField66;
    private javax.swing.JFormattedTextField jFormattedTextField67;
    private javax.swing.JFormattedTextField jFormattedTextField68;
    private javax.swing.JFormattedTextField jFormattedTextField69;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField70;
    private javax.swing.JFormattedTextField jFormattedTextField71;
    private javax.swing.JFormattedTextField jFormattedTextField72;
    private javax.swing.JFormattedTextField jFormattedTextField73;
    private javax.swing.JFormattedTextField jFormattedTextField74;
    private javax.swing.JFormattedTextField jFormattedTextField75;
    private javax.swing.JFormattedTextField jFormattedTextField76;
    private javax.swing.JFormattedTextField jFormattedTextField77;
    private javax.swing.JFormattedTextField jFormattedTextField78;
    private javax.swing.JFormattedTextField jFormattedTextField79;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField80;
    private javax.swing.JFormattedTextField jFormattedTextField81;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    // End of variables declaration//GEN-END:variables
    
}
